#!/usr/bin/env python

#
# Copyright (c) 2011 Per Andersson
#
# This file is part of mlogr.
#
# mlogr is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# mlogr is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with mlogr.  If not, see <http://www.gnu.org/licenses/>.
#

import sys
sys.path.append("src")
from mlogr import mlogr, exception

try:
    mlogr(sys.argv)
except exception.MlogrException, e:
    print >>sys.stderr, unicode(e)
    sys.exit(2)
except exception.MlogrConfigException, e:
    print >>sys.stderr, unicode(e)
    mlogr.usage()
    sys.exit(2)
